import React from 'react';
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { render, screen, waitFor,fireEvent } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import axios from 'axios';
import CityWeather from '../Pages/CityWeather';

jest.mock('axios');
const mockedAxios = axios as jest.Mocked<typeof axios>;

const mockApiResponse = {
  location: { name: 'Delhi', country: 'India' },
  current: {
    temp_c: 30,
    condition: { text: 'Sunny', icon: '//cdn.weatherapi.com/weather/64x64/day/113.png' },
    last_updated: '2024-06-01 10:00',
    humidity: 50,
    wind_kph: 10,
    cloud: 20,
  },
  forecast: {
    forecastday: [
      {
        date: '2024-06-01',
        day: { maxtemp_c: 35, mintemp_c: 25, condition: { text: 'Sunny', icon: '//cdn.weatherapi.com/weather/64x64/day/113.png' } },
        hour: [
          {
            time: '2024-06-01 10:00',
            temp_c: 30,
            condition: { text: 'Sunny', icon: '//cdn.weatherapi.com/weather/64x64/day/113.png' },
          },
        ],
      },
      // ...add more days if needed
    ],
  },
};

describe('CityWeather', () => {
  test('renders weather data for a city', async () => {
    // Code Generated by Sidekick is for learning and experimentation purposes only.
    mockedAxios.get.mockResolvedValueOnce({
      data: mockApiResponse,
      status: 200,
      statusText: 'OK',
      headers: {},
      config: { url: 'https://api.weatherapi.com/v1/forecast.json' },
    });

    render(
      <MemoryRouter initialEntries={['/city/Delhi']}>
        <Routes>
          <Route path="/city/:cityName" element={<CityWeather />} />
        </Routes>
      </MemoryRouter>
    );

    // Loading state
    expect(screen.getByText(/Loading/i)).toBeInTheDocument();

    // Wait for weather data to appear
    await waitFor(() => {
      expect(screen.getByText(/Delhi/i)).toBeInTheDocument();
      expect(screen.getAllByText(/Sunny/i).length).toBeGreaterThan(0);
    });
     });

      test('renders loading state', async () => {
    // Code Generated by Sidekick is for learning and experimentation purposes only.
    mockedAxios.get.mockResolvedValueOnce({
      data: mockApiResponse,
      status: 200,
      statusText: 'OK',
      headers: {},
      config: {url: 'https://api.weatherapi.com/v1/forecast.json'},
    });

    render(
      <MemoryRouter initialEntries={['/city/Delhi']}>
        <Routes>
          <Route path="/city/:cityName" element={<CityWeather />} />
        </Routes>
      </MemoryRouter>
    );

    // Loading should be visible immediately
    expect(screen.getByText(/Loading/i)).toBeInTheDocument();

    // Wait for data to load
    await waitFor(() => {
      expect(screen.getByText(/Delhi/i)).toBeInTheDocument();
    });
  });



   test('switches temperature unit on toggle', async () => {
    mockedAxios.get.mockResolvedValueOnce({
      data: mockApiResponse,
      status: 200,
      statusText: 'OK',
      headers: {},
      config: {url:'https://api.weatherapi.com/v1/forecast.json'},
    });

    render(
      <MemoryRouter initialEntries={['/city/Delhi']}>
        <Routes>
          <Route path="/city/:cityName" element={<CityWeather />} />
        </Routes>
      </MemoryRouter>
    );

    await waitFor(() => {
      expect(screen.getAllByText(/30.0/i).length).toBeGreaterThan(0); 
    });

    // Click °F toggle button
    fireEvent.click(screen.getByText('°F'));

    // Now temp should be in Fahrenheit (86.0)
    await waitFor(() => {
      expect(screen.getAllByText(/86.0/i).length).toBeGreaterThan(0);
    });
  });

  
});