import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import Header from '../Component/Header';


// Mock navigate function
const mockNavigate = jest.fn();

// react-router-dom ko mock karo, useNavigate ko custom function se
jest.mock('react-router-dom', () => {
  // Code Generated by Sidekick is for learning and experimentation purposes only.
  const actual = jest.requireActual('react-router-dom');
  return {
    ...actual,
    useNavigate: () => mockNavigate,
  };
});

describe('Header Component', () => {
  beforeEach(() => {
    mockNavigate.mockClear();
  });



 it('renders logo link with correct text', () => {

  //rendering header component
    render(
      <MemoryRouter>
        <Header />
      </MemoryRouter>
    );

    //Search for logo text 
    const logo = screen.getByText(/WW⚡/i);

    //check logo page present in UI or not
    expect(logo).toBeInTheDocument();

    //Check whether logo is link which will navigate to home("/") page
    expect(logo.closest('a')).toHaveAttribute('href', '/');
  });



   it('renders input field and search button', () => {
    render(
      <MemoryRouter>
        <Header />
      </MemoryRouter>
    );

    //Search input field 
    const input = screen.getByPlaceholderText(/Search by City/i);

    // looking for "Search" button whether is it there or not
    const button = screen.getByRole('button', { name: /search/i });

    //Check whether present in UI or not
    expect(input).toBeInTheDocument();
    expect(button).toBeInTheDocument();
  });



  it('updates input value on change', () => {
    render(
      <MemoryRouter>
        <Header />
      </MemoryRouter>
    );

    //HTMLInputElement = “TypeScript, treat this element as an <input> element, jismein .value property hoti hai.”
    //Search input field
    const input = screen.getByPlaceholderText(/Search by City/i) as HTMLInputElement;

    //setting value of input as "Delhi"
    fireEvent.change(input, { target: { value: 'Delhi' } });

    //Checks wether input filed value is "Delhi" or not
    expect(input.value).toBe('Delhi');
  });



   it('calls navigate with correct city name on form submit', () => {
    // Creating mock function
    const mockNavigate = jest.fn();

    //whenever the useNavigate will get call it will return mockNavigate function instead of original 
    jest.spyOn(require('react-router-dom'), 'useNavigate').mockImplementation(() => mockNavigate);

    render(
      <MemoryRouter>
        <Header />
      </MemoryRouter>
    );

    //searching for input field and button
    const input = screen.getByPlaceholderText(/Search by City/i);
    const button = screen.getByRole('button', { name: /search/i });

    //Passing "Mumbai" as input
    fireEvent.change(input, { target: { value: 'Mumbai' } });
    fireEvent.click(button);

    expect(mockNavigate).toHaveBeenCalledWith('/Mumbai');
  });


  it('does not call navigate if input is empty or whitespace', () => {
    render(
      <MemoryRouter>
        <Header />
      </MemoryRouter>
    );
    const input = screen.getByPlaceholderText(/Search by City/i);
    const button = screen.getByRole('button', { name: /search/i });

    // Whitespace
    fireEvent.change(input, { target: { value: '   ' } });
    fireEvent.click(button);
    expect(mockNavigate).not.toHaveBeenCalled();

    // Empty
    fireEvent.change(input, { target: { value: '' } });
    fireEvent.click(button);
    expect(mockNavigate).not.toHaveBeenCalled();
  });

});